python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
python Client.py &
echo "Client started"
wait
