curl -X GET "http://localhost:8000/test_db_multiple/1" &
curl -X GET "http://localhost:8000/test_db_multiple/2" &
curl -X GET "http://localhost:8000/test_db_multiple/3" &
curl -X GET "http://localhost:8000/test_db_multiple/4" &
curl -X GET "http://localhost:8000/test_db_multiple/5" &
curl -X GET "http://localhost:8000/test_db_multiple/6" &
curl -X GET "http://localhost:8000/test_db_multiple/7" &
curl -X GET "http://localhost:8000/test_db_multiple/8" &
curl -X GET "http://localhost:8000/test_db_multiple/9" &
curl -X GET "http://localhost:8000/test_db_multiple/10" &
curl -X GET "http://localhost:8000/test_db_multiple/11" &
curl -X GET "http://localhost:8000/test_db_multiple/12" &
curl -X GET "http://localhost:8000/test_db_multiple/13" &
curl -X GET "http://localhost:8000/test_db_multiple/14" &
curl -X GET "http://localhost:8000/test_db_multiple/15" &
curl -X GET "http://localhost:8000/test_db_multiple/16" &
curl -X GET "http://localhost:8000/test_db_multiple/17" &
curl -X GET "http://localhost:8000/test_db_multiple/18" &
curl -X GET "http://localhost:8000/test_db_multiple/19" &
curl -X GET "http://localhost:8000/test_db_multiple/20" &
curl -X GET "http://localhost:8000/test_db_multiple/21" &
curl -X GET "http://localhost:8000/test_db_multiple/22" &
curl -X GET "http://localhost:8000/test_db_multiple/23" &
curl -X GET "http://localhost:8000/test_db_multiple/24" &
curl -X GET "http://localhost:8000/test_db_multiple/25" &
curl -X GET "http://localhost:8000/test_db_multiple/26" &
curl -X GET "http://localhost:8000/test_db_multiple/27" &
curl -X GET "http://localhost:8000/test_db_multiple/28" &
curl -X GET "http://localhost:8000/test_db_multiple/29" &
curl -X GET "http://localhost:8000/test_db_multiple/30" &
curl -X GET "http://localhost:8000/test_db_multiple/31" &
curl -X GET "http://localhost:8000/test_db_multiple/32" &
curl -X GET "http://localhost:8000/test_db_multiple/33" &
curl -X GET "http://localhost:8000/test_db_multiple/34" &
curl -X GET "http://localhost:8000/test_db_multiple/35" &
curl -X GET "http://localhost:8000/test_db_multiple/36" &
curl -X GET "http://localhost:8000/test_db_multiple/37" &
curl -X GET "http://localhost:8000/test_db_multiple/38" &
curl -X GET "http://localhost:8000/test_db_multiple/39" &
curl -X GET "http://localhost:8000/test_db_multiple/40" &
echo "All tests started"
wait